services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

#docker-compose -f docker-compose-kafka.yml up -d
#docker exec -it kafka /bin/sh
#./bin/kafka-topics.sh --create--zookeeper zookeeper:2181 --replication-factor 1 --partitions 1 --topic patients